[2017/03/20 12:37:15] :: [pool-1-thread-15] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2017/03/20 12:37:15] :: [pool-1-thread-15] :: Current Thread Name for the test is "pool-1-thread-15"<br><br>[2017/03/20 12:37:47] :: [pool-1-thread-15] :: The user has launched 'http://test.salesforce.com<br><br>[2017/03/20 12:37:48] :: [pool-1-thread-15] :: The user has creating NONINVPaidorder<br><br>[2017/03/20 12:38:07] :: [pool-1-thread-15] :: arindom.das@move.com.qa has successfully loggedin<br><br>[2017/03/20 12:38:41] :: [pool-1-thread-15] :: Exception occurred. null<br><br>[2017/03/20 12:38:46] :: [pool-1-thread-15] :: Closing the Browser Instance<br><br>[2017/03/20 12:38:46] :: [pool-1-thread-15] ::  File Name: Assert.java Method name: fail(91)<br> File Name: Assert.java Method name: assertTrue(43)<br> File Name: Assert.java Method name: assertTrue(54)<br> File Name: Common.java Method name: changeStatusSales(161)<br> File Name: SalesForce.java Method name: loginSF(100)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/AMENDMENT/Modify_NonInventory_Paid_TPCRM_DL.feature Method name: When I login to SalesForce(7)<br><br>Complete Error Message: <br><br><br>