[2018/01/04 13:08:14] :: [pool-1-thread-15] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2018/01/04 13:08:14] :: [pool-1-thread-15] :: Current Thread Name for the test is "pool-1-thread-15"<br><br>[2018/01/04 13:08:32] :: [pool-1-thread-15] :: The user has launched 'https://qainc--qa.cs30.my.salesforce.com<br><br>[2018/01/04 13:08:33] :: [pool-1-thread-15] :: The user has creating SalesCancel_Invorder<br><br>[2018/01/04 13:08:57] :: [pool-1-thread-15] :: arindom.das@move.com.qa has successfully loggedin<br><br>[2018/01/04 13:09:28] :: [pool-1-thread-15] :: Unable to navigate to Home page<br><br>[2018/01/04 13:09:32] :: [pool-1-thread-15] :: Closing the Browser Instance<br><br>[2018/01/04 13:09:32] :: [pool-1-thread-15] ::  File Name: Assert.java Method name: fail(86)<br> File Name: Assert.java Method name: assertTrue(41)<br> File Name: Assert.java Method name: assertTrue(52)<br> File Name: SalesForce.java Method name: verifyHP(198)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/AMD_CANCEL/New_Sales_Cancel_Inventory_Connections(SM)for_Seller_Bundle _DL.feature Method name: Then I should be in "Home" page(8)<br><br>Complete Error Message: null<br><br><br>