[2017/09/02 12:54:19] :: [pool-1-thread-30] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2017/09/02 12:54:19] :: [pool-1-thread-30] :: Current Thread Name for the test is "pool-1-thread-30"<br><br>[2017/09/02 12:54:31] :: [pool-1-thread-30] :: The user has launched 'https://moveinc.my.salesforce.com<br><br>[2017/09/02 12:54:47] :: [pool-1-thread-30] :: arindom.das@move.com has successfully loggedin<br><br>[2017/09/02 12:54:47] :: [pool-1-thread-30] :: The user has creating accountIDorder<br><br>[2017/09/02 12:55:34] :: [pool-1-thread-30] :: Successfully clicked on SearchButton .<br><br>[2017/09/02 12:55:49] :: [pool-1-thread-30] :: Exception occurred. 1<br><br>[2017/09/02 12:55:53] :: [pool-1-thread-30] :: Closing the Browser Instance<br><br>[2017/09/02 12:55:53] :: [pool-1-thread-30] ::  File Name: Assert.java Method name: fail(86)<br> File Name: Assert.java Method name: assertTrue(41)<br> File Name: Assert.java Method name: assertTrue(52)<br> File Name: Productions.java Method name: i_pick_account_id(885)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/A2C-get AccountID c-21/GetAccoutIDC-21AdvantageNewOrder9.feature Method name: And I pick account "9"(8)<br><br>Complete Error Message: null<br><br><br>