[2017/06/25 12:38:23] :: [pool-1-thread-4] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2017/06/25 12:38:23] :: [pool-1-thread-4] :: Current Thread Name for the test is "pool-1-thread-4"<br><br>[2017/06/25 12:38:33] :: [pool-1-thread-4] :: The user has launched 'https://moveinc.my.salesforce.com<br><br>[2017/06/25 12:38:47] :: [pool-1-thread-4] :: arindom.das@move.com has successfully loggedin<br><br>[2017/06/25 12:38:50] :: [pool-1-thread-4] :: The user has creating accountIDorder<br><br>[2017/06/25 12:39:27] :: [pool-1-thread-4] :: Successfully clicked on SearchButton .<br><br>[2017/06/25 12:40:38] :: [pool-1-thread-4] :: Exception occurred. 1<br><br>[2017/06/25 12:40:42] :: [pool-1-thread-4] :: Closing the Browser Instance<br><br>[2017/06/25 12:40:42] :: [pool-1-thread-4] ::  File Name: Assert.java Method name: fail(86)<br> File Name: Assert.java Method name: assertTrue(41)<br> File Name: Assert.java Method name: assertTrue(52)<br> File Name: Productions.java Method name: i_pick_account_id(857)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/A2B-AccountID/Copy (2) of Copy (2) of GetAccoutIDC-21AdvantageNewOrder.feature Method name: And I pick account "6"(8)<br><br>Complete Error Message: null<br><br><br>