[2017/03/07 11:55:15] :: [pool-1-thread-8] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2017/03/07 11:55:15] :: [pool-1-thread-8] :: Current Thread Name for the test is "pool-1-thread-8"<br><br>[2017/03/07 11:55:57] :: [pool-1-thread-8] :: The user has launched 'http://test.salesforce.com<br><br>[2017/03/07 11:55:57] :: [pool-1-thread-8] :: The user has creating RetBuyoutNONorder<br><br>[2017/03/07 11:57:21] :: [pool-1-thread-8] :: arindom.das@move.com.qa has successfully loggedin<br><br>[2017/03/07 11:57:22] :: [pool-1-thread-8] :: Successfully navigated to Home page<br><br>[2017/03/07 11:57:22] :: [pool-1-thread-8] :: File path is = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\ .<br><br>[2017/03/07 11:58:00] :: [pool-1-thread-8] :: Successfully Assets Type is visible= Advantage .<br><br>[2017/03/07 11:58:08] :: [pool-1-thread-8] :: Successfully Account ID is visible= 001j000000bferV .<br><br>[2017/03/07 11:58:32] :: [pool-1-thread-8] :: Successfully Account Name is visible 001j000000bferV .<br><br>[2017/03/07 11:58:53] :: [pool-1-thread-8] :: Successfully Enter contact email<br><br>[2017/03/07 11:58:53] :: [pool-1-thread-8] :: Exception occurred. C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\SalesForce\OutPutData.xlsx (The process cannot access the file because it is being used by another process)<br><br>[2017/03/07 11:58:55] :: [pool-1-thread-8] :: Closing the Browser Instance<br><br>[2017/03/07 11:58:55] :: [pool-1-thread-8] ::  File Name: Assert.java Method name: fail(91)<br> File Name: Assert.java Method name: assertTrue(43)<br> File Name: Assert.java Method name: assertTrue(54)<br> File Name: Common.java Method name: changeContactEmail(851)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/AMDMAIL/AMDMAIL/Copy (5) of ContactEmailChangeForAllTC.feature Method name: And change contact Email(10)<br><br>Complete Error Message: <br><br><br>