[2017/09/08 12:34:36] :: [pool-1-thread-15] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2017/09/08 12:34:37] :: [pool-1-thread-15] :: Current Thread Name for the test is "pool-1-thread-15"<br><br>[2017/09/08 12:34:51] :: [pool-1-thread-15] :: The user has launched 'https://moveinc.my.salesforce.com<br><br>[2017/09/08 12:35:51] :: [pool-1-thread-15] :: arindom.das@move.com has successfully loggedin<br><br>[2017/09/08 12:36:23] :: [pool-1-thread-15] :: Exception occurred. null<br><br>[2017/09/08 12:36:27] :: [pool-1-thread-15] :: Closing the Browser Instance<br><br>[2017/09/08 12:36:27] :: [pool-1-thread-15] ::  File Name: Assert.java Method name: fail(86)<br> File Name: Assert.java Method name: assertTrue(41)<br> File Name: Assert.java Method name: assertTrue(52)<br> File Name: Common.java Method name: changeStatusSales(166)<br> File Name: SalesForce.java Method name: loginSF(101)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/A2C-get AccountID c-21/GetAccoutIDC-21AdvantageNewOrder22.feature Method name: When I login to SalesForce(6)<br><br>Complete Error Message: null<br><br><br>