[2017/10/16 16:53:32] :: [pool-1-thread-2] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2017/10/16 16:53:32] :: [pool-1-thread-2] :: Current Thread Name for the test is "pool-1-thread-2"<br><br>[2017/10/16 16:53:43] :: [pool-1-thread-2] :: The user has launched 'https://qainc--qa.cs30.my.salesforce.com<br><br>[2017/10/16 16:53:44] :: [pool-1-thread-2] :: The user has creating ARJoborder<br><br>[2017/10/16 16:54:00] :: [pool-1-thread-2] :: arindom.das@move.com.qa has successfully loggedin<br><br>[2017/10/16 16:54:02] :: [pool-1-thread-2] :: Successfully navigated to Home page<br><br>[2017/10/16 16:54:03] :: [pool-1-thread-2] :: Exception occurred. For input string: "<AssetID>"<br><br>[2017/10/16 16:54:14] :: [pool-1-thread-2] :: Closing the Browser Instance<br><br>[2017/10/16 16:54:14] :: [pool-1-thread-2] ::  File Name: Assert.java Method name: fail(86)<br> File Name: Assert.java Method name: assertTrue(41)<br> File Name: Assert.java Method name: assertTrue(52)<br> File Name: Common.java Method name: loginUserNameAccountID(782)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/Ar_SanityJob2/SFDCARJobSanityCheck3.feature Method name: When I login with "" and launch "<AssetID>"(9)<br><br>Complete Error Message: null<br><br><br>