[2017/04/28 15:44:08] :: [pool-1-thread-2] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2017/04/28 15:44:08] :: [pool-1-thread-2] :: Current Thread Name for the test is "pool-1-thread-2"<br><br>[2017/04/28 15:45:03] :: [pool-1-thread-2] :: The user has launched 'http://test.salesforce.com<br><br>[2017/04/28 15:45:25] :: [pool-1-thread-2] :: arindom.das@move.com.qa has successfully loggedin<br><br>[2017/04/28 15:45:28] :: [pool-1-thread-2] :: Successfully navigated to Home page<br><br>[2017/04/28 15:45:35] :: [pool-1-thread-2] :: Exception occurred. null<br><br>[2017/04/28 15:45:39] :: [pool-1-thread-2] :: Exception occurred. null value in entry: url=null<br><br>[2017/04/28 15:45:46] :: [pool-1-thread-2] :: Closing the Browser Instance<br><br>[2017/04/28 15:45:46] :: [pool-1-thread-2] ::  File Name: Assert.java Method name: fail(91)<br> File Name: Assert.java Method name: assertTrue(43)<br> File Name: Assert.java Method name: assertTrue(54)<br> File Name: Commissions.java Method name: PrintingFiledExcelReport(3491)<br> File Name: Commissions.java Method name: erifyingParentAssetZuoraDetails(215)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/Clawback_Commissions/Copy (2) of Copy (2) of Inventory_ClawBack_Commissions_CrossOverDateAmendCancel.feature Method name: Then I am verifying parent asset zuora details using "00217181" and "CrossOverDateAmendOrCancelNonInventory" and "Market Snapshot"(8)<br><br>Complete Error Message: <br><br><br>