[2018/01/17 12:35:32] :: [pool-1-thread-3] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2018/01/17 12:35:33] :: [pool-1-thread-3] :: Current Thread Name for the test is "pool-1-thread-3"<br><br>[2018/01/17 12:35:47] :: [pool-1-thread-3] :: The user has launched 'https://qainc--qa.cs30.my.salesforce.com<br><br>[2018/01/17 12:36:02] :: [pool-1-thread-3] :: arindom.das@move.com.qa has successfully loggedin<br><br>[2018/01/17 12:36:03] :: [pool-1-thread-3] :: The user has creating SalesCancel_NonInvorder<br><br>[2018/01/17 12:36:04] :: [pool-1-thread-3] :: Successfully navigated to Home page<br><br>[2018/01/17 12:36:06] :: [pool-1-thread-3] :: File path is = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\ .<br><br>[2018/01/17 12:36:13] :: [pool-1-thread-3] :: Exception occurred. org.apache.poi.openxml4j.exceptions.InvalidFormatException: Package should contain a content type part [M1.13]<br><br>[2018/01/17 12:36:19] :: [pool-1-thread-3] :: Closing the Browser Instance<br><br>[2018/01/17 12:36:21] :: [pool-1-thread-3] ::  File Name: Assert.java Method name: fail(86)<br> File Name: Assert.java Method name: assertTrue(41)<br> File Name: Assert.java Method name: assertTrue(52)<br> File Name: sfdc.java Method name: loginUserNameAccountID(395)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/Cancel/New_Sales_Buyout_Inventory_DAP_EUT_DL.feature Method name: When I am entering "Emily Morrison" and launch "2"(9)<br><br>Complete Error Message: null<br><br><br>