[2017/09/09 16:22:59] :: [pool-1-thread-1] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2017/09/09 16:22:59] :: [pool-1-thread-1] :: Current Thread Name for the test is "pool-1-thread-1"<br><br>[2017/09/09 16:23:13] :: [pool-1-thread-1] :: The user has launched 'https://moveinc.my.salesforce.com<br><br>[2017/09/09 16:23:30] :: [pool-1-thread-1] :: arindom.das@move.com has successfully loggedin<br><br>[2017/09/09 16:23:34] :: [pool-1-thread-1] :: The user has creating accountIDorder<br><br>[2017/09/09 16:23:53] :: [pool-1-thread-1] :: Exception occurred. 2<br><br>[2017/09/09 16:23:58] :: [pool-1-thread-1] :: Closing the Browser Instance<br><br>[2017/09/09 16:23:58] :: [pool-1-thread-1] ::  File Name: Assert.java Method name: fail(86)<br> File Name: Assert.java Method name: assertTrue(41)<br> File Name: Assert.java Method name: assertTrue(52)<br> File Name: Productions.java Method name: i_pick_account_id(886)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/A2C-get AccountID c-21/GetAccoutIDC-21AdvantageNewOrder.feature Method name: And I pick account "1"(8)<br><br>Complete Error Message: null<br><br><br>